name: PikaOS Build

on: push

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pikaos-linux/pika-package-container:latest
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Update apt cache
      run: apt-get update

    - name: Build Package
      run: ./main.sh
